<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
      xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
      xmlns:itsm="urn:oio:atp:itsm:casemanagement:1.0.0"  
      xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
      xmlns:qlm="http://iet.atp.dk/2006/QlmInformation/" 
      targetNamespace="urn:oio:atp:itsm:casemanagement:1.0.0" 
      name="CaseManagement">
  <wsdl:documentation>
    <ServiceName>CaseManagement</ServiceName>
  </wsdl:documentation>
  <wsdl:types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="urn:oio:atp:itsm:casemanagement:1.0.0">
      <xsd:include schemaLocation="CreateCaseVendor.xsd"/>
      <xsd:include schemaLocation="CreateCaseVendorResponse.xsd"/> 
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="CreateCaseVendorMessage">
    <wsdl:part name="CreateCaseVendorBody" element="itsm:CreateCaseVendor"/>
  </wsdl:message>
  <wsdl:message name="CreateCaseVendorResponseMessage">
    <wsdl:part name="CreateCaseVendorResponseBody" element="itsm:CreateCaseVendorResponse"/>
  </wsdl:message>
  <wsdl:portType name="CaseManagementInterface">
    <wsdl:operation name="CreateCaseVendor">
      <wsdl:input name="CreateCaseVendorIn" message="itsm:CreateCaseVendorMessage">		
      </wsdl:input>
      <wsdl:output name="CreateCaseVendorOut" message="itsm:CreateCaseVendorResponseMessage">	
      </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CaseManagementBinding" type="itsm:CaseManagementInterface">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="CreateCaseVendor">
      <soap:operation soapAction="urn:oio:atp:itsm:casemanagement:1.0.0:#CreateCaseVendor"/>
      <wsdl:input name="CreateCaseVendorIn">
        <soap:body parts="CreateCaseVendorBody" use="literal"/>
      </wsdl:input>
      <wsdl:output name="CreateCaseVendorOut">
        <soap:body parts="CreateCaseVendorResponseBody" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding> 
  <wsdl:service name="CaseManagement">
    <wsdl:port binding="itsm:CaseManagementBinding" name="CaseManagement">
      <soap:address location="http://ws.atp.dk/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
