<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
      xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
      xmlns:itsm="urn:oio:atp:itsm:casemanagement:1.0.0"  
      xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
      xmlns:qlm="http://iet.atp.dk/2006/QlmInformation/" 
      targetNamespace="urn:oio:atp:itsm:casemanagement:1.0.0" 
      name="CaseManagement">
  <wsdl:documentation>
    <ServiceName>CaseManagement</ServiceName>
  </wsdl:documentation>
  <wsdl:types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="urn:oio:atp:itsm:casemanagement:1.0.0">
      <xsd:include schemaLocation="UpdateCase.xsd"/>
      <xsd:include schemaLocation="UpdateCaseResponse.xsd"/> 
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="UpdateCaseMessage">
    <wsdl:part name="UpdateCaseBody" element="itsm:UpdateCase"/>
  </wsdl:message>
  <wsdl:message name="UpdateCaseResponseMessage">
    <wsdl:part name="UpdateCaseResponseBody" element="itsm:UpdateCaseResponse"/>
  </wsdl:message>
  <wsdl:portType name="CaseManagementInterface">
    <wsdl:operation name="UpdateCase">
      <wsdl:input name="UpdateCaseIn" message="itsm:UpdateCaseMessage">		
      </wsdl:input>
      <wsdl:output name="UpdateCaseOut" message="itsm:UpdateCaseResponseMessage">	
      </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CaseManagementBinding" type="itsm:CaseManagementInterface">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="UpdateCase">
      <soap:operation soapAction="urn:oio:atp:itsm:casemanagement:1.0.0:#UpdateCase"/>
      <wsdl:input name="UpdateCaseIn">
        <soap:body parts="UpdateCaseBody" use="literal"/>
      </wsdl:input>
      <wsdl:output name="UpdateCaseOut">
        <soap:body parts="UpdateCaseResponseBody" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding> 
  <wsdl:service name="CaseManagement">
    <wsdl:port binding="itsm:CaseManagementBinding" name="CaseManagement">
      <soap:address location="http://ws.atp.dk/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
